# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-service
  labels:
    app: custom-nginx
spec:
  type: LoadBalancer  # 클러스터 외부에서 접근할 수 있도록 LoadBalancer로 설정
  ports:
  - port: 80          # 외부에서 접근할 포트
    targetPort: 80    # 컨테이너 내부에서 노출된 포트
  selector:
    app: custom-nginx
