apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-app
spec:
  replicas: 4
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.20  # 현재 배포 중인 이미지 버전
        ports:
        - containerPort: 80

