apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-app-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: example-app
  minReplicas: 4                     # 최소 Pod 개수를 Rollout의 초기 설정과 동일하게.
  maxReplicas: 6                    # 최대 Pod 개수.
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50       # CPU 사용률 50%를 기준으로 확장.

