apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example-app-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: example-app
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10 # Pod 축소 안정화 대기 시간 (기본 300초에서 10초로 줄임)
      policies:
      - type: Percent
        value: 50      # Pod 개수를 50%씩 줄임
        periodSeconds: 10  # Pod 축소 간격 10초
      - type: Pods
        value: 2       # 한 번에 최대 2개의 Pod 축소
        periodSeconds: 10
    scaleUp:
      stabilizationWindowSeconds: 0 # Pod 증가 시 안정화 대기 시간 제거

