apiVersion: v1
kind: Service
metadata:
  name: example-app-service  # 서비스 이름을 명확히 지정
  labels:
    app: example-app
spec:
  type: LoadBalancer  # 클러스터 외부에서 접근할 수 있도록 LoadBalancer로 설정
  selector:
    app: example-app  # Deployment의 레이블과 일치해야 함
  ports:
    - name: http
      protocol: TCP
      port: 80          # 외부에서 접근할 포트
      targetPort: 80    # 컨테이너 내부에서 노출된 포트
