apiVersion: v1
kind: Service
metadata:
  name: example-app
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # 노드 포트를 고정하려면 여기 추가 (옵션)
  type: NodePort

