# Stable 배포 설정
stable:
  replicaCount: 3  # Stable 버전의 Pod 수 (대부분의 트래픽을 처리)

# Canary 배포 설정
canary:
  replicaCount: 1  # Canary 버전의 Pod 수 (일부 트래픽만 처리)

image:
  repository: paperdoll96/keduitlab  # Docker 이미지 저장소
  stableTag: yellow  # Stable 버전의 이미지 태그
  canaryTag: pupple  # Canary 버전의 이미지 태그
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

hpa:
  minReplicas: 3
  maxReplicas: 6
  averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
      value: 50
      periodSeconds: 10
      maxPods: 2
    scaleUp:
      stabilizationWindowSeconds: 0

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

