apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-example-app-stable
  labels:
    app: {{ .Release.Name }}-example-app
    version: stable
spec:
  replicas: {{ .Values.stable.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-example-app
      version: stable
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-example-app
        version: stable
    spec:
      containers:
        - name: example-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.stableTag }}"
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-example-app-canary
  labels:
    app: {{ .Release.Name }}-example-app
    version: canary
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-example-app
      version: canary
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-example-app
        version: canary
    spec:
      containers:
        - name: example-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.canaryTag }}"
          ports:
            - containerPort: 80

