apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-example-app-service  # 서비스 이름을 Helm Release와 연동
  labels:
    app: {{ .Release.Name }}-example-app
spec:
  type: {{ .Values.service.type }}  # Service 유형을 템플릿화 (LoadBalancer 등)
  selector:
    app: {{ .Release.Name }}-example-app  # Deployment와 일치하는 레이블
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}          # 외부에서 접근할 포트
      targetPort: {{ .Values.service.targetPort }}    # 컨테이너 내부에서 노출된 포트

